spring:
  sql:
    init:
      schema-locations:
        - classpath:/sql/init.sql
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://the-sign.net/login/oauth2/code/google
          kakao:
            redirect-uri: http://the-sign.net/login/oauth2/code/kakao

