spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      encoding: UTF-8

  profiles:
    include:
      - oauth

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access:
    expiration: 3600000
  refresh:
    expiration: 1209600000
