spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations:
        - classpath:/sql/member_schema.sql
        - classpath:/sql/room_schema.sql
        - classpath:/sql/joins_schema.sql
      encoding: UTF-8
      mode: always

  profiles:
    include: oauth

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access:
    expiration: 3600000
  refresh:
    expiration: 1209600000
