DROP TABLE IF EXISTS `JOINS`;

CREATE TABLE JOINS (
  JOIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  MEMBER_ID BIGINT,
  ROOM_ID BIGINT,
  CREATED_DATE DATETIME NOT NULL,
  FOREIGN KEY (MEMBER_ID) REFERENCES Member (MEMBER_ID),
  FOREIGN KEY (ROOM_ID) REFERENCES Room (CLASSROOM_ID)
);