DROP TABLE IF EXISTS `JOINS`;

CREATE TABLE JOINS (
  MEMBER_ID BIGINT,
  ROOM_ID BIGINT,
  CREATED_DATE DATETIME NOT NULL,
  ENTERED_AT DATETIME NOT NULL,

  PRIMARY KEY (MEMBER_ID, ROOM_ID),

  FOREIGN KEY (MEMBER_ID) REFERENCES Member (MEMBER_ID),
  FOREIGN KEY (ROOM_ID) REFERENCES Room (CLASSROOM_ID)
) default character set utf8 collate utf8_general_ci;