DROP TABLE IF EXISTS `ROOM`;

CREATE TABLE ROOM (
  CLASSROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(255) UNIQUE,
  capacity INT NOT NULL,
  MEMBER_ID BIGINT,
  FOREIGN KEY (MEMBER_ID) REFERENCES Member (MEMBER_ID)
);
